num = int(input('Enter a number: '))
print('-'*10)
print('{0} x  1 = {1}'.format(num,num*1))
print('{0} x  2 = {1}'.format(num,num*2))
print('{0} x  3 = {1}'.format(num,num*3))
print('{0} x  4 = {1}'.format(num,num*4))
print('{0} x  5 = {1}'.format(num,num*5))
print('{0} x  6 = {1}'.format(num,num*6))
print('{0} x  7 = {1}'.format(num,num*7))
print('{0} x  8 = {1}'.format(num,num*8))
print('{0} x  9 = {1}'.format(num,num*9))
print('{0} x 10 = {1}'.format(num,num*10))
print('-'*10)
